Fix undefined method `split' for nil related error
It's causing spec/models/github_issue_spec.rb:179, spec/services/last_sync_timestamp_finder_spec.rb:130 & spec/services/sync_options_builder_spec.rb:69 realted specs to fail